// Generated by the Maven Archetype Plug-in
package br.com.doit.superheroes.app;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WORequest;

import br.com.doit.superheroes.components.Main;
import er.extensions.appserver.ERXDirectAction;

public class DirectAction extends ERXDirectAction {
	public DirectAction( WORequest request ) {
		super( request );
	}

	public WOActionResults defaultAction() {
		return pageWithName( Main.class.getName() );
	}
}
